### ISSUE TITLE
batch book loads and duplicate page labels

### ISSUE THREAD

**Issue by lydiam** [FLVC/flvc#3]
On fiu-test the same book doesn’t have any duplicate pages, but there are two pages named *_033:  https://fiu-test.digital.flvc.org/islandora/object/fiu%3A1066/pages?page=4

Randy's comment:  
"The duplicated labels are required for repeated pages, so that there won't be repeats in the bookreader.   It does show up in the TOC.   Odd I know..  Here's the relevant mail from Gail:
So there's no error there.  It's a feature, not a bug!
Of course it's possible I misunderstood Gail's message,  I'll let her weigh in if necessary."

I'm opening an issue so that this doesn't get lost over the holiday break.

**Comment by grf** [comment]
Problem resolved;   there were two issues - construction of the  JSON table of contents for two presentations - that of the pages themselves,  and for the book reader, which treat the data is subtly different ways.   In addition, in many cases prior to the fix, pages where actually uploaded twice (as separate objects),  so that a fix to existing books exhibiting the problem require structural changes to the rel-ext data streams and a deletion of the repeated pages.

It may be easier to re-ingest the problematic books.

**Comment by grf** [comment]
I believe this problem is resolved; there were two issues - construction of the JSON table of contents for two presentations - that of the pages themselves, and for the book reader, which treat the data is subtly different ways. In addition, in many cases prior to the fix, pages where actually uploaded twice (as separate objects), so that a fix to existing books exhibiting the problem require structural changes to the rel-ext data streams and a deletion of the repeated pages.

It may be easier to re-ingest the problematic books.

New code put to test servers (load and presentation servers) as well as development servers.

**Comment by lydiam** [comment]
Mike and Lydia will be loading a sampling of problem packages and comparing results.  We may want to do this for all affected book packages prior to reloading on the production server.

**Comment by grf** [comment]
Lydia and Mike find it adequate.
