### ISSUE TITLE
Islandora Person Entities not linking to department Organization Entities, if the Organization Entity or its parent Organization Entity have an ampersand in the department name

### ISSUE THREAD

**Issue by wrandtkeflvc** [FLVC/flvc#59]
All faculty Person Entities and department Organization Entities are created on https://fgcu-test.digital.flvc.org/ .

When clicking "Repository" and browsing the department tree, if any department Organization Entity in the chain has an ampersand in the name, then the Person Entities aren't linked to it.

I tried editing MADS for the department Organization Entities, and editing MADS for the Person Entities.  When I edit the MADS for a Person Entity, and let the department name autofill, then save, it still doesn't link up.

**Comment by glewisorg** [comment]
This should be fixed now.  It was an indexing problem.  I reindexed all FGCU person objects.  One object was still not working due to a misspelled department.  I corrected the MADS.

https://fgcu-test.digital.flvc.org/islandora/object/fgcu%3A2305

A couple others weren't working due to "&amp;" in the object label.  I changed them back to "&".

**Comment by glewisorg** [comment]
Trying again - can't have "amp;" in the label.

**Comment by wrandtkeflvc** [comment]
This is working now and is resolved.  I'll go ahead and close the issue.
